# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/csmajs/jmann028/Filmify

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/csmajs/jmann028/Filmify

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/csmajs/jmann028/Filmify/CMakeFiles /home/csmajs/jmann028/Filmify//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/csmajs/jmann028/Filmify/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named run

# Build rule for target.
run: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run
.PHONY : run

# fast build rule for target.
run/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/build
.PHONY : run/fast

src/Movie.o: src/Movie.cpp.o
.PHONY : src/Movie.o

# target to build an object file
src/Movie.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/Movie.cpp.o
.PHONY : src/Movie.cpp.o

src/Movie.i: src/Movie.cpp.i
.PHONY : src/Movie.i

# target to preprocess a source file
src/Movie.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/Movie.cpp.i
.PHONY : src/Movie.cpp.i

src/Movie.s: src/Movie.cpp.s
.PHONY : src/Movie.s

# target to generate assembly for a file
src/Movie.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/Movie.cpp.s
.PHONY : src/Movie.cpp.s

src/MovieDataSet.o: src/MovieDataSet.cpp.o
.PHONY : src/MovieDataSet.o

# target to build an object file
src/MovieDataSet.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/MovieDataSet.cpp.o
.PHONY : src/MovieDataSet.cpp.o

src/MovieDataSet.i: src/MovieDataSet.cpp.i
.PHONY : src/MovieDataSet.i

# target to preprocess a source file
src/MovieDataSet.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/MovieDataSet.cpp.i
.PHONY : src/MovieDataSet.cpp.i

src/MovieDataSet.s: src/MovieDataSet.cpp.s
.PHONY : src/MovieDataSet.s

# target to generate assembly for a file
src/MovieDataSet.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/MovieDataSet.cpp.s
.PHONY : src/MovieDataSet.cpp.s

src/MovieMethods.o: src/MovieMethods.cpp.o
.PHONY : src/MovieMethods.o

# target to build an object file
src/MovieMethods.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/MovieMethods.cpp.o
.PHONY : src/MovieMethods.cpp.o

src/MovieMethods.i: src/MovieMethods.cpp.i
.PHONY : src/MovieMethods.i

# target to preprocess a source file
src/MovieMethods.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/MovieMethods.cpp.i
.PHONY : src/MovieMethods.cpp.i

src/MovieMethods.s: src/MovieMethods.cpp.s
.PHONY : src/MovieMethods.s

# target to generate assembly for a file
src/MovieMethods.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/MovieMethods.cpp.s
.PHONY : src/MovieMethods.cpp.s

src/inputoutput.o: src/inputoutput.cpp.o
.PHONY : src/inputoutput.o

# target to build an object file
src/inputoutput.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/inputoutput.cpp.o
.PHONY : src/inputoutput.cpp.o

src/inputoutput.i: src/inputoutput.cpp.i
.PHONY : src/inputoutput.i

# target to preprocess a source file
src/inputoutput.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/inputoutput.cpp.i
.PHONY : src/inputoutput.cpp.i

src/inputoutput.s: src/inputoutput.cpp.s
.PHONY : src/inputoutput.s

# target to generate assembly for a file
src/inputoutput.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/inputoutput.cpp.s
.PHONY : src/inputoutput.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... run"
	@echo "... src/Movie.o"
	@echo "... src/Movie.i"
	@echo "... src/Movie.s"
	@echo "... src/MovieDataSet.o"
	@echo "... src/MovieDataSet.i"
	@echo "... src/MovieDataSet.s"
	@echo "... src/MovieMethods.o"
	@echo "... src/MovieMethods.i"
	@echo "... src/MovieMethods.s"
	@echo "... src/inputoutput.o"
	@echo "... src/inputoutput.i"
	@echo "... src/inputoutput.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

